# Generated by Django 3.2.8 on 2021-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('2', models.CharField(max_length=100)), ('1', models.CharField(max_length=100)), ('3', models.CharField(max_length=100)), ('4', models.CharField(max_length=100))], max_length=100)),
            ],
        ),
    ]
