# Generated by Django 3.2.8 on 2021-10-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('3', models.CharField(max_length=100)), ('2', models.CharField(max_length=100)), ('4', models.CharField(max_length=100)), ('1', models.CharField(max_length=100))], max_length=100),
        ),
    ]
